module.exports = [
  {
    title: 'Pregnancy Support Pillow',
    slug: 'pregnancy-support-pillow',
    description: 'Ergonomic C-shaped pillow for side-sleep comfort during second & third trimester.',
    price: 39.99,
    currency: 'GBP',
    brand: 'SoftNest',
    category: 'sleep',
    images: ['https://images.unsplash.com/photo-1582582429416-87f9f0b0f35a?q=80&w=1200&auto=format'],
    inStock: true,
    rating: 4.8,
    tags: ['comfort', 'sleep', 'trimester-2'],
    recommendedWeek: 16,
    url: 'https://example.com/pillow'
  },
  {
    title: 'Prenatal Vitamins (30-Day)',
    slug: 'prenatal-vitamins-30',
    description: 'Balanced prenatal vitamin with folic acid, iron, and DHA.',
    price: 14.5,
    currency: 'GBP',
    brand: 'HealthFirst',
    category: 'supplements',
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1200&auto=format'],
    inStock: true,
    rating: 4.6,
    tags: ['health', 'daily'],
    recommendedWeek: 0,
    url: 'https://example.com/prenatal'
  },
  {
    title: 'BPA-Free Baby Bottles (2-Pack)',
    slug: 'bpa-free-bottles-2pack',
    description: 'Anti-colic design, newborn-friendly silicone nipple.',
    price: 11.99,
    currency: 'GBP',
    brand: 'TinyCare',
    category: 'feeding',
    images: ['https://images.unsplash.com/photo-1603715749722-d223bad95388?q=80&w=1200&auto=format'],
    inStock: true,
    rating: 4.7,
    tags: ['newborn', 'feeding'],
    recommendedWeek: 38,
    url: 'https://example.com/bottles'
  },
  {
    title: 'Organic Muslin Swaddles (3-Pack)',
    slug: 'organic-muslin-swaddles-3',
    description: 'Breathable 100% cotton swaddles, 120Ã120cm.',
    price: 18.99,
    currency: 'GBP',
    brand: 'PureWeave',
    category: 'newborn',
    images: ['https://images.unsplash.com/photo-1567899378494-47b22a2ae96f?q=80&w=1200&auto=format'],
    inStock: true,
    rating: 4.9,
    tags: ['swaddle', 'hospital-bag'],
    recommendedWeek: 36,
    url: 'https://example.com/swaddles'
  },
  {
    title: 'Postpartum Recovery Kit',
    slug: 'postpartum-recovery-kit',
    description: 'Peri bottle, cooling pads, briefsâhospital bag essential.',
    price: 29.0,
    currency: 'GBP',
    brand: 'RecoverEase',
    category: 'postpartum',
    images: ['https://images.unsplash.com/photo-1582719478250-2a9e2df80891?q=80&w=1200&auto=format'],
    inStock: true,
    rating: 4.5,
    tags: ['postpartum', 'kit'],
    recommendedWeek: 40,
    url: 'https://example.com/postpartum-kit'
  }
];
